# docker-compose.yml

version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
